kind: Pod
apiVersion: v1
metadata:
  name: mysql-server
  labels:
    app: myapp
    role: server
spec:
  containers:
  - name: mysql-server
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password  
    resources:
      requests:
        cpu: 0.1
        memory: 256Mi
---

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: UGFzc3dvckQ=
 
---

apiVersion: v1
kind: Service
metadata: 
  name: mysql
spec: 
  selector:
    app: myapp
    role: server
   ports:
   - port: 3306

   
--- 

apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  labels:
    app: myapp
    role: client
spec: 
  containers: 
  - name: mysql-client
    image: nidzelska/mysql-git
    command: ["sleep"]
    args: ["3600"]
    env:
    - name: PASSWORD
      valueFrom: 
          secretKeyRef:
            name: mysecret
            key: password
    resources:
      requests:
        cpu: 0.05
        memory: 64Mi
    


