---
kind: Service
apiVersion: v1
metadata:
  name: web
spec:
  selector:
    application: www
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: www
  template:
    metadata:
      labels:
        application: www
    spec:

      initContainers:
      - name: initor
        image: nidzelska/nginx-curl
        command: ['sh', '-c', 'curl MAIN_PAGE >>/usr/share/nginx/html/index.html']
        volumeMounts:
          - name: nginx-pv
            mountPath: /usr/share/nginx/html

      containers:
      - name: nginx
        image: nidzelska/nginx-curl
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /usr/share/nginx/html
            name: nginx-pv

      volumes:
        - name: nginx-pv
          emptyDir: {}
